### ISSUE TITLE
Validation needed for fault injection because target might not have L7 layer

### ISSUE THREAD

**Issue by esnible** [istio/manager#406] opened 2017-03-28 15:31 UTC
For example, if a service doesn't have a port named with `http` prefix it will be treated as TCP, even if it is doing HTTP.

Adding route-rules with faults against this port should be considered an error.

Note that this means that to work with Istio a Kubernetes *Deployment* must have a port.  It isn't sufficient to leave the port off the Deployment description and specify it when creating the Service.  To set a name for an anonymous port, a K8s user may do `kubectl patch deployment <DEPLOYMENT> --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/ports/0/name", "value":"http"}]'` before or after injecting the Istio proxy.

**Comment by andraxylia** [comment] 2017-03-28 18:25
Since k8s protocol spec only allows tcp and udp as possible fields, the user must prefix the field "name" of the port with "http", "https", "http2", "grpc", to indicate the port is used for l7. Document this requirement.

**Comment by rshriram** [comment] 2017-03-31 18:49
Closing this, as a duplicate of #418

**Closed by rshriram** 2017-03-31 18:49 UTC
Labels: UX (User)
