### ISSUE TITLE
Validate rules and polices before istioctl sends them to kube client

### ISSUE THREAD

**Issue by esnible** [istio/manager#423] opened 2017-03-30 19:14 UTC
The first implementation will be of the simple rules in issue #418

**Comment by rshriram** [comment] 2017-03-31 18:43
why do we need another issue for the same issue ? Given that we are going to have a server side API, I would suggest that we just focus on #418, develop the validation library, use it temporarily and then when we have the server side, we can reuse it on server side.

**Comment by rshriram** [comment] 2017-03-31 18:50
Closing this issue as duplicate of #418

**Closed** 2017-03-31 18:50 UTC
Labels: UX (User)
