### ISSUE TITLE
Istioctl version incorrectly requires ISTIO_MANAGER_ADDRESS to be set

### ISSUE THREAD

**Issue by liamawhite** [istio/manager#679] opened 2017-05-06 19:59 UTC
As none of the info it returns require a manager side call this is a bug

**Comment by rshriram** [comment] 2017-05-06 21:22
I think the original intent was to let the users see the service mesh version (manager, route rules schemes, mixer, config schemes, etc).

**Comment by mukundha** [comment] 2017-05-08 12:21
should i run the istioctl inside the k8s cluster or create a LB type istio-manager? looks like `istioctl create -f route-rule-all-v1.yaml` uses the `ISTIO_MANAGER_ADDRESS` to make API calls

**Comment by ldemailly** [comment] 2017-05-08 18:53
Duplicate of #637

**Closed by ldemailly** 2017-05-08 18:53 UTC
