### ISSUE TITLE
bin/e2e.sh fails with "routing verification failed" 

### ISSUE THREAD

**Issue by ayj** [istio/manager#356] opened 2017-03-18 04:12 UTC
```
$ git rev-parse HEAD
e5cd59b6d6675a2bdc68bdab1290d073afcc4921

$ [bin/e2e.sh](url) --count 100 -debug
<snip>

2017/03/18 03:49:07 Error Get http://world/hello: EOF
I0317 20:49:07.436324   30305 driver.go:145] routing verification failed
```

Ful test output [here](https://gist.github.com/ayj/f34e8e0ac7c5b0795c30fb102fba5e2a). 
List of running processes and logs for the manager and proxy containers [here](https://storage.googleapis.com/ayj0/upstream-connect-error.tar).

**Comment by ayj** [comment] 2017-03-18 05:29
This issue might be caused by high CPU load on cluster nodes during the test.

ref https://github.com/istio/manager/issues/292 (possibly perf related issue)

**Comment by kyessenov** [comment] 2017-04-06 04:14
Marking as duplicate of #292 since logs indicate "rds: fetch failures".

**Closed** 2017-04-06 04:14 UTC
Labels: bug
