### ISSUE TITLE
Add appropriate lyft.github.io/envoy references to proxy/envoy/* source

### ISSUE THREAD

**Issue by ayj** [istio/manager#487] opened 2017-04-10 15:53 UTC
It would be helpful to include additional references to envoy documentation in the proxy agent source code. For example, proxy/envoy/discovery.go should include a reference to the SDS/CDS/RDS at https://lyft.github.io/envoy.

**Comment by rshriram** [comment] 2017-04-12 15:36
@ayj closing this as duplicate of #427 . And assigning #427 to you instead.

**Closed by rshriram** 2017-04-12 15:36 UTC
Labels: debuggability
