### ISSUE TITLE
istioctl get not working

### ISSUE THREAD

**Issue by frankbu** [istio/manager#654] opened 2017-05-03 19:34 UTC
`istioctl get route-rule` isn't working anymore. 
In the [routing task](https://istio.io/docs/tasks/request-routing.html), creating the rules works, but the get's fail.
```
Franks-MacBook-Pro:bookinfo frankbudinsky$ istioctl create -f route-rule-all-v1.yaml
Created config: route-rule productpage-default
Created config: route-rule reviews-default
Created config: route-rule ratings-default
Created config: route-rule details-default
Franks-MacBook-Pro:bookinfo frankbudinsky$ istioctl get route-rules -o yaml
<no output>
```
```
Franks-MacBook-Pro:bookinfo frankbudinsky$ istioctl create -f route-rule-reviews-test-v2.yaml
Created config: route-rule reviews-test-v2
Franks-MacBook-Pro:bookinfo frankbudinsky$ istioctl get route-rule reviews-test-v2
Error: received non-success status code 404 with message item with key default/route-rule-reviews-test-v2 not found
```
The rules have, however, been set and are working as expected.
We should make sure to add `istioctl get` to the e2e test.

**Comment by esnible** [comment] 2017-05-03 23:17
Probably a duplicate of #653 and the problem is on the server.

**Closed** 2017-05-04 15:00 UTC
Labels: bug, duplicate
