### ISSUE TITLE
Kubernetes Admission Controller for proxy injection

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#57] opened 2017-01-25 22:45 UTC

**Comment by rshriram** [comment] 2017-01-26 02:13
Bit more detail? Are we writing our own?

**Comment by kyessenov** [comment] 2017-01-26 02:19
Yes, we need to inject sidecar proxy container to automate pod spec rewrite. There is no platform support, so the issue is track the upstream progress.

**Comment by ayj** [comment] 2017-01-26 04:15
ref [Proposal: Extensible Admission Control](https://github.com/kubernetes/community/pull/132/)

**Comment by ayj** [comment] 2017-03-15 23:56
Duplicate of https://github.com/istio/manager/issues/335

**Closed by ayj** 2017-03-15 23:56 UTC
Labels: platform, tracking
